# Generated by Django 5.1.7 on 2025-03-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
